from apps.shared.demo_colors import demo_color_for

DEMO_TIME_ZONE = "UTC"
DEMO_PASSWORD = "password123"
PASSWORD_ROUNDS = 12
SPREAD_FIRST_DAY = -45
SPREAD_LAST_DAY = 60
RESPONDED_DAY = -2
RESPONDED_HOUR = 12

ALEX = "alex.morgan@calendar.com"
JORDAN = "jordan.smith@calendar.com"
TAYLOR = "taylor.johnson@calendar.com"
RILEY = "riley.parker@calendar.com"
CASEY = "casey.bennett@calendar.com"

PROFILE_ROWS = [
    {
        "name": "Alex Morgan",
        "email": ALEX,
        "avatarColor": demo_color_for(ALEX),
        "isProfile": True,
        "sortOrder": 1,
        "timeZone": DEMO_TIME_ZONE,
        "workingHours": {"startMinute": 540, "endMinute": 1050},
    },
    {
        "name": "Jordan Smith",
        "email": JORDAN,
        "avatarColor": demo_color_for(JORDAN),
        "isProfile": True,
        "sortOrder": 2,
        "timeZone": DEMO_TIME_ZONE,
        "workingHours": {"startMinute": 540, "endMinute": 1020},
    },
    {
        "name": "Taylor Johnson",
        "email": TAYLOR,
        "avatarColor": demo_color_for(TAYLOR),
        "isProfile": True,
        "sortOrder": 3,
        "timeZone": DEMO_TIME_ZONE,
        "workingHours": {"startMinute": 600, "endMinute": 1080},
    },
    {
        "name": "Riley Parker",
        "email": RILEY,
        "avatarColor": demo_color_for(RILEY),
        "isProfile": True,
        "sortOrder": 4,
        "timeZone": DEMO_TIME_ZONE,
        "workingHours": {"startMinute": 480, "endMinute": 990},
    },
    {
        "name": "Casey Bennett",
        "email": CASEY,
        "avatarColor": demo_color_for(CASEY),
        "isProfile": True,
        "sortOrder": 5,
        "timeZone": DEMO_TIME_ZONE,
        "workingHours": {"startMinute": 540, "endMinute": 1020},
    },
]

RECURRING_TEMPLATES = [
    {
        "owner": ALEX,
        "calendar": "work",
        "title": "Weekly product planning",
        "description": "Review priorities, risks, and the next delivery window.",
        "location": "Conference room Maple",
        "startDay": -7,
        "startMinute": 600,
        "endDay": -7,
        "endMinute": 660,
        "recurrence": {"frequency": "weekly"},
        "guests": [JORDAN, TAYLOR, RILEY],
        "statuses": ["accepted", "accepted", "tentative"],
    },
    {
        "owner": ALEX,
        "title": "Office",
        "type": "workingLocation",
        "description": "Working from the office today.",
        "location": "Office",
        "startDay": -7,
        "startMinute": 0,
        "endDay": -6,
        "endMinute": 0,
        "allDay": True,
        "recurrence": {"frequency": "weekly", "daysOfWeek": [2, 4]},
    },
    {
        "owner": JORDAN,
        "calendar": "work",
        "title": "Delivery stand-up",
        "description": "Daily progress and blockers.",
        "startDay": -8,
        "startMinute": 555,
        "endDay": -8,
        "endMinute": 570,
        "recurrence": {"frequency": "weekdays", "count": 60},
        "guests": [RILEY],
        "statuses": ["accepted"],
    },
    {
        "owner": JORDAN,
        "title": "Home",
        "type": "workingLocation",
        "description": "Working remotely.",
        "location": "Home",
        "startDay": -9,
        "startMinute": 0,
        "endDay": -8,
        "endMinute": 0,
        "allDay": True,
        "recurrence": {"frequency": "weekly", "daysOfWeek": [1, 3]},
    },
    {
        "owner": TAYLOR,
        "calendar": "work",
        "title": "Design critique",
        "description": "Review the responsive Month and Week experiences.",
        "location": "Studio",
        "startDay": -6,
        "startMinute": 900,
        "endDay": -6,
        "endMinute": 960,
        "recurrence": {"frequency": "weekly", "count": 14},
        "guests": [CASEY],
        "statuses": ["accepted"],
    },
    {
        "owner": RILEY,
        "title": "One-on-one",
        "description": "Weekly coaching conversation.",
        "startDay": -5,
        "startMinute": 840,
        "endDay": -5,
        "endMinute": 870,
        "recurrence": {"frequency": "weekly", "count": 16},
        "guests": [JORDAN],
        "statuses": ["accepted"],
    },
    {
        "owner": CASEY,
        "calendar": "work",
        "title": "Launch check-in",
        "description": "Confirm launch dependencies and owners.",
        "startDay": -8,
        "startMinute": 660,
        "endDay": -8,
        "endMinute": 690,
        "recurrence": {"frequency": "weekly", "count": 14},
        "guests": [ALEX, JORDAN],
        "statuses": ["accepted", "accepted"],
    },
]

SPREAD_TEMPLATES = [
    {
        "owner": ALEX,
        "calendar": "work",
        "title": "Design review",
        "description": "Review the current product flow and resolve open decisions.",
        "location": "Conference room Cedar",
        "hour": 10,
        "minutes": 60,
        "guests": [TAYLOR, CASEY],
        "statuses": ["accepted", "tentative"],
    },
    {
        "owner": ALEX,
        "title": "Focus time",
        "type": "focusTime",
        "description": "Protected time for the release-readiness write-up.",
        "hour": 14,
        "minutes": 90,
    },
    {
        "owner": ALEX,
        "title": "Publish weekly update",
        "type": "task",
        "description": "Summarize decisions, owners, and next steps.",
        "hour": 16,
        "minutes": 30,
    },
    {
        "owner": JORDAN,
        "calendar": "work",
        "title": "Project sync",
        "description": "Review delivery status and clear blockers.",
        "location": "Conference room Birch",
        "hour": 9,
        "minutes": 45,
        "guests": [RILEY],
        "statuses": ["accepted"],
    },
    {
        "owner": JORDAN,
        "title": "Customer discovery",
        "description": "Understand the current scheduling workflow.",
        "location": "Video call",
        "hour": 13,
        "minutes": 60,
        "guests": [CASEY],
        "statuses": ["accepted"],
    },
    {
        "owner": TAYLOR,
        "title": "Research review",
        "description": "Synthesize usability-study findings.",
        "hour": 15,
        "minutes": 60,
        "guests": [ALEX],
        "statuses": ["needsAction"],
    },
    {
        "owner": TAYLOR,
        "title": "Prototype exploration",
        "type": "focusTime",
        "hour": 11,
        "minutes": 120,
    },
    {
        "owner": RILEY,
        "calendar": "work",
        "title": "Engineering review",
        "description": "Review architecture, reliability, and rollout risks.",
        "location": "Conference room Pine",
        "hour": 11,
        "minutes": 60,
        "guests": [JORDAN, ALEX],
        "statuses": ["accepted", "tentative"],
    },
    {
        "owner": RILEY,
        "title": "Incident drill",
        "description": "Practice the service-recovery playbook.",
        "location": "Operations room",
        "hour": 15,
        "minutes": 60,
    },
    {
        "owner": CASEY,
        "calendar": "work",
        "title": "Campaign planning",
        "description": "Coordinate launch messages and channel owners.",
        "location": "Conference room Willow",
        "hour": 12,
        "minutes": 60,
        "guests": [ALEX, TAYLOR],
        "statuses": ["accepted", "accepted"],
    },
    {
        "owner": CASEY,
        "title": "Editorial review",
        "description": "Final review of the release announcement.",
        "hour": 16,
        "minutes": 60,
        "guests": [TAYLOR],
        "statuses": ["tentative"],
    },
    {
        "owner": ALEX,
        "title": "Health appointment",
        "description": "Annual preventive check-up.",
        "location": "Community clinic",
        "hour": 17,
        "minutes": 60,
    },
    {
        "owner": JORDAN,
        "title": "Code review",
        "type": "focusTime",
        "description": "Review the authentication and recurrence changes.",
        "hour": 15,
        "minutes": 90,
    },
    {
        "owner": TAYLOR,
        "title": "Update accessibility notes",
        "type": "task",
        "hour": 16,
        "minutes": 30,
    },
    {
        "owner": RILEY,
        "title": "Rotate service credentials",
        "type": "task",
        "hour": 11,
        "minutes": 30,
    },
    {
        "owner": CASEY,
        "title": "Agency call",
        "description": "Review the next creative delivery.",
        "location": "Video call",
        "hour": 17,
        "minutes": 45,
    },
    {
        "owner": ALEX,
        "calendar": "work",
        "title": "Team roadmap",
        "description": "Align priorities for the next milestone.",
        "location": "Orchid",
        "hour": 11,
        "minutes": 60,
        "guests": [JORDAN, TAYLOR],
        "statuses": ["accepted", "tentative"],
    },
    {
        "owner": JORDAN,
        "title": "Deep work",
        "type": "focusTime",
        "hour": 10,
        "minutes": 120,
    },
    {
        "owner": TAYLOR,
        "calendar": "work",
        "title": "Content workshop",
        "description": "Improve empty, loading, and error-state language.",
        "location": "Conference room Elm",
        "hour": 11,
        "minutes": 90,
        "guests": [ALEX, JORDAN],
        "statuses": ["accepted", "declined"],
    },
    {
        "owner": RILEY,
        "calendar": "work",
        "title": "Release readiness",
        "description": "Verify tests, monitoring, and rollback steps.",
        "hour": 10,
        "minutes": 60,
        "guests": [ALEX, JORDAN, TAYLOR],
        "statuses": ["accepted", "accepted", "needsAction"],
    },
    {
        "owner": CASEY,
        "title": "Write launch brief",
        "type": "focusTime",
        "hour": 10,
        "minutes": 120,
    },
    {
        "owner": ALEX,
        "title": "Read research notes",
        "type": "task",
        "hour": 18,
        "minutes": 30,
    },
]

EVENTS_PER_DAY_ROTATION = [3, 1, 2, 4, 2, 3, 1, 2]
TEMPLATE_DAY_STRIDE = 3
TEMPLATE_SLOT_STRIDE = 7
SLOT_STEP_MINUTES = 30
SLOT_STEP_COUNT = 24

DAY_OFF_PREFERENCES = [
    {"owner": ALEX, "preferred": 21, "description": "Unavailable for meetings."},
    {"owner": JORDAN, "preferred": 10, "description": "Unavailable for the day."},
    {"owner": TAYLOR, "preferred": 24, "description": "Unavailable all day."},
    {"owner": RILEY, "preferred": 31, "description": "Unavailable for the day."},
    {"owner": CASEY, "preferred": 16, "description": "Unavailable for meetings."},
]

MILESTONES_BEFORE_DAYS_OFF = [
    {
        "owner": ALEX,
        "calendar": "birthdays",
        "title": "Jordan’s birthday",
        "description": "Birthday reminder.",
        "startDay": 3,
        "startMinute": 0,
        "endDay": 4,
        "endMinute": 0,
        "allDay": True,
    },
]

MILESTONES_AFTER_DAYS_OFF = [
    {
        "owner": TAYLOR,
        "title": "Out of office",
        "type": "outOfOffice",
        "description": "Unavailable after lunch.",
        "startDay": 4,
        "startMinute": 780,
        "endDay": 4,
        "endMinute": 1080,
    },
    {
        "owner": ALEX,
        "title": "Office hours",
        "type": "appointmentSchedule",
        "description": "Open slots for project questions.",
        "location": "Video call",
        "startDay": 6,
        "startMinute": 900,
        "endDay": 6,
        "endMinute": 1020,
    },
    {
        "owner": JORDAN,
        "title": "Mentoring slots",
        "type": "appointmentSchedule",
        "description": "Book a 30-minute mentoring conversation.",
        "startDay": 12,
        "startMinute": 840,
        "endDay": 12,
        "endMinute": 960,
    },
    {
        "owner": TAYLOR,
        "title": "Portfolio review slots",
        "type": "appointmentSchedule",
        "description": "Book a portfolio walkthrough.",
        "startDay": 18,
        "startMinute": 840,
        "endDay": 18,
        "endMinute": 960,
    },
    {
        "owner": RILEY,
        "title": "Technical office hours",
        "type": "appointmentSchedule",
        "description": "Open slots for architecture questions.",
        "startDay": 27,
        "startMinute": 900,
        "endDay": 27,
        "endMinute": 1020,
    },
    {
        "owner": CASEY,
        "title": "Communications office hours",
        "type": "appointmentSchedule",
        "description": "Open slots for launch messaging.",
        "startDay": 9,
        "startMinute": 660,
        "endDay": 9,
        "endMinute": 780,
    },
]

TAYLOR_AFTERNOON_BLOCK = {"owner": TAYLOR, "day": 4, "startMinute": 780, "endMinute": 1080}
